[project]
name = "hallu"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "black>=25.11.0",
    "fastparquet>=2024.11.0",
    "torch-geometric>=2.7.0",
    "zensols-calamr==0.3.0",
]
